# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Welcome', folder: 'pages', file: 'welcome.html'}
- {name: 'Projects', folder: 'pages', file: 'projects.html'}
- {name: 'Monitoring', folder: 'pages', file: 'monitoring.html'}
- {name: 'Collaborations', folder: 'pages', file: 'collaborations.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Credits', folder: 'pages', file: 'credits.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/GallegatiAndrea'}
- {icon: 'facebook', link: 'https://www.facebook.com/a.gallegati/'}
#- {icon: 'instagram', link: 'https://www.instagram.com/a.gallegati/'}
- {icon: 'flickr', link: 'https://www.flickr.com/photos/andreagalle/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/andrea-gallegati/'}
- {icon: 'envelope', link: 'mailto:andreagalle@hotmail.it'}
#- {icon: 'rss-square', link: 'feed.xml'}
## - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
